# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://carmenherrerafoundation.org'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Carmen Herrera Foundation
# Description of the Site
description: Supporting the artistic legacy of Carmen Herrera
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Carmen Herrera, Foundation
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/simonletort/WhatATheme/master/assets/images/CH.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username: carmen-herrera-foundation 
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: 
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/simonletort/WhatATheme/master/assets/images/CH-portrait.jpg
# 60 Words About the Author
author-about: The Foundation supports the artistic legacy of Carmen Herrera. We are engaged in a comprehensive project to research and publish catalogues raisonnés that illustrate and detail the artist's work, and are committed to supporting other scholarship on the artist and exhibitions of her work around the world.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
